/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.LivroDAO;
import Controle.MetodosAuxiliares;
import static com.oracle.jrockit.jfr.DataType.UTF8;
import com.sun.glass.events.MouseEvent;
import java.awt.Event;
import java.awt.Image;
import java.awt.dnd.DropTarget;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import jdk.nashorn.internal.runtime.JSType;
import sun.font.TrueTypeFont;

/**
 *
 * @author JYRAYA
 */
public class Inclusao extends javax.swing.JFrame {

    /**
     * Creates new form Inclusao
     */
    public Inclusao() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLtitulofoto = new javax.swing.JLabel();
        jLimagem = new javax.swing.JLabel();
        jLtitulo = new javax.swing.JLabel();
        jTFtitulo = new javax.swing.JTextField();
        jLdescricao = new javax.swing.JLabel();
        jSPdescricao = new javax.swing.JScrollPane();
        jTAdescricao = new javax.swing.JTextArea();
        jLautor = new javax.swing.JLabel();
        jTFautor = new javax.swing.JTextField();
        jLeditora = new javax.swing.JLabel();
        jTFeditora = new javax.swing.JTextField();
        jLisbn = new javax.swing.JLabel();
        jTFisbn = new javax.swing.JTextField();
        jLpaginas = new javax.swing.JLabel();
        jTFpaginas = new javax.swing.JTextField();
        jLpag_lidas = new javax.swing.JLabel();
        jTFpg_lidas = new javax.swing.JTextField();
        jLadquirido = new javax.swing.JLabel();
        jBconfirmar = new javax.swing.JButton();
        jBcancelar = new javax.swing.JButton();
        jBselecionar = new javax.swing.JButton();
        jTFimagem = new javax.swing.JTextField();
        jCBadquirido = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLtitulodajanela = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLtitulofoto.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLtitulofoto.setText("FOTO");

        jLimagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jLtitulo.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLtitulo.setText("Título");

        jTFtitulo.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        jLdescricao.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLdescricao.setText("Descrição");

        jTAdescricao.setColumns(20);
        jTAdescricao.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jTAdescricao.setLineWrap(true);
        jTAdescricao.setRows(5);
        jSPdescricao.setViewportView(jTAdescricao);

        jLautor.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLautor.setText("Autor");

        jTFautor.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        jLeditora.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLeditora.setText("Editora");

        jTFeditora.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        jLisbn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLisbn.setText("ISBN");

        jTFisbn.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jTFisbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFisbnActionPerformed(evt);
            }
        });

        jLpaginas.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLpaginas.setText("Páginas");

        jTFpaginas.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        jLpag_lidas.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLpag_lidas.setText("Páginas lidas");

        jTFpg_lidas.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jTFpg_lidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFpg_lidasActionPerformed(evt);
            }
        });

        jLadquirido.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLadquirido.setText("Adquirido");

        jBconfirmar.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jBconfirmar.setText("Confirmar");
        jBconfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBconfirmarActionPerformed(evt);
            }
        });

        jBcancelar.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jBcancelar.setText("Cancelar");
        jBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarActionPerformed(evt);
            }
        });

        jBselecionar.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jBselecionar.setText("Selecionar");
        jBselecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBselecionarActionPerformed(evt);
            }
        });

        jTFimagem.setEditable(false);
        jTFimagem.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jTFimagem.setEnabled(false);
        jTFimagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFimagemActionPerformed(evt);
            }
        });

        jCBadquirido.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jCBadquirido.setText("Sim / Não");
        jCBadquirido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBadquiridoActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLtitulodajanela.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLtitulodajanela.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLtitulodajanela.setText("Inclusão de Livros");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/addBook.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(72, 72, 72)
                .addComponent(jLtitulodajanela)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLtitulodajanela)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLtitulofoto))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFimagem, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(jLimagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBselecionar)))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jBconfirmar)
                        .addGap(52, 52, 52)
                        .addComponent(jBcancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLdescricao, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLeditora, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLautor, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLtitulo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLisbn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLpaginas, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLadquirido, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTFpaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLpag_lidas)
                                .addGap(18, 18, 18)
                                .addComponent(jTFpg_lidas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCBadquirido)
                            .addComponent(jTFisbn)
                            .addComponent(jTFeditora)
                            .addComponent(jSPdescricao)
                            .addComponent(jTFtitulo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTFautor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLtitulo)
                    .addComponent(jLtitulofoto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFautor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLautor))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSPdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLdescricao))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFeditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLeditora))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFisbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLisbn))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLpaginas)
                            .addComponent(jTFpaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLpag_lidas)
                            .addComponent(jTFpg_lidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLadquirido)
                            .addComponent(jCBadquirido))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBconfirmar)
                            .addComponent(jBcancelar))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLimagem, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTFimagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBselecionar)
                        .addGap(150, 150, 150))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBconfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBconfirmarActionPerformed
        //int id_livro = Integer.parseInt((jTFid.getText()));
        String foto = jTFimagem.getText();
        String titulo = jTFtitulo.getText();
        String descricao = jTAdescricao.getText();
        String autor = jTFautor.getText();
        String editora = jTFeditora.getText();
        String isbn = jTFisbn.getText();
        int paginas = Integer.parseInt((jTFpaginas.getText()));
        int pag_lidas = Integer.parseInt((jTFpg_lidas.getText()));
        
        boolean validapagina = true;
        boolean validaisbn = true;
        String str = isbn;
         
        if (str.matches("[0-9]+") && jTFisbn.getText().length() <= 13) {
            
            
        } else {
            JOptionPane.showMessageDialog(null, "ISBN inválido! O campo de ISBN deve aceitar apenas números e no máximo 13");
            validaisbn = false;
        }
         
        if(pag_lidas > paginas){
            JOptionPane.showMessageDialog(null, "Número de páginas lidas maior que paginas do livro");
            pag_lidas = Integer.parseInt((jTFpg_lidas.getText()));
            validapagina = false;
        }
        
        String adquirido = "";
        if(jCBadquirido.isSelected()){
            adquirido = "SIM";
        }else{
            adquirido = "NÃO";
        }
        
        if(validapagina == true && validaisbn == true){
            LivroDAO.incluir(/*id_livro,*/foto, titulo, descricao, autor, editora, isbn, paginas, pag_lidas, adquirido);
            
            int op = JOptionPane.showConfirmDialog(null, "Deseja Realizar outro cadastro?", "Menssagem", JOptionPane.YES_NO_OPTION);
            if (op == JOptionPane.YES_OPTION) {
                //jTFid.setText();
                jTFimagem.setText("");
                jLimagem.setIcon(null);
                jTFtitulo.setText("");
                jTAdescricao.setText("");
                jTFautor.setText("");
                jTFeditora.setText("");
                jTFisbn.setText("");
                jTFisbn.setText("");
                jTFpaginas.setText("");
                jTFpg_lidas.setText("");
                jCBadquirido.setSelected(false);

            } else {
                dispose();

            }
        }
       
        
        
    }//GEN-LAST:event_jBconfirmarActionPerformed

    private void jBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jBcancelarActionPerformed

    private void jBselecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBselecionarActionPerformed
        JFileChooser arquivo = new JFileChooser();
        int janela = arquivo.showOpenDialog(null);
        if (janela == JFileChooser.APPROVE_OPTION) {
            File file = arquivo.getSelectedFile();
            jTFimagem.setText(String.valueOf(file));
            Image imagem = getToolkit().getImage(jTFimagem.getText());
            String nome = file.getAbsoluteFile().getName();
            
            String os = "";
            os = System.getProperty("os.name");
            
            String ori = "";
            String des = "";
            
            if(os.equals("Windows 10")){
                ori = jTFimagem.getText();
                des = ".\\Fotos\\" + nome;
            }else{
                ori = jTFimagem.getText();
                des = ".//Fotos//" + nome;
            }
           
            try {
                MetodosAuxiliares.copiar(ori, des);
                jTFimagem.setText(des);
            } catch (IOException ex) {
                Logger.getLogger(Inclusao.class.getName()).log(Level.SEVERE, null, ex);
            }
            imagem = getToolkit().getImage(jTFimagem.getText());
            int altura = jLimagem.getHeight();
            int largura = jLimagem.getWidth();
            imagem = imagem.getScaledInstance(largura, altura, Image.SCALE_DEFAULT);
            jLimagem.setIcon(new ImageIcon(imagem));
              
        }
    }//GEN-LAST:event_jBselecionarActionPerformed

    
    private void jTFimagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFimagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFimagemActionPerformed

    private void jTFisbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFisbnActionPerformed
       
    }//GEN-LAST:event_jTFisbnActionPerformed

    private void jTFpg_lidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFpg_lidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFpg_lidasActionPerformed

    private void jCBadquiridoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBadquiridoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBadquiridoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inclusao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inclusao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inclusao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inclusao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inclusao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcancelar;
    private javax.swing.JButton jBconfirmar;
    private javax.swing.JButton jBselecionar;
    private javax.swing.JCheckBox jCBadquirido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLadquirido;
    private javax.swing.JLabel jLautor;
    private javax.swing.JLabel jLdescricao;
    private javax.swing.JLabel jLeditora;
    private javax.swing.JLabel jLimagem;
    private javax.swing.JLabel jLisbn;
    private javax.swing.JLabel jLpag_lidas;
    private javax.swing.JLabel jLpaginas;
    private javax.swing.JLabel jLtitulo;
    private javax.swing.JLabel jLtitulodajanela;
    private javax.swing.JLabel jLtitulofoto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jSPdescricao;
    private javax.swing.JTextArea jTAdescricao;
    private javax.swing.JTextField jTFautor;
    private javax.swing.JTextField jTFeditora;
    private javax.swing.JTextField jTFimagem;
    private javax.swing.JTextField jTFisbn;
    private javax.swing.JTextField jTFpaginas;
    private javax.swing.JTextField jTFpg_lidas;
    private javax.swing.JTextField jTFtitulo;
    // End of variables declaration//GEN-END:variables
}
