/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.LivroDAO;
import Controle.MetodosAuxiliares;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Lab1
 */
public class Selecao extends javax.swing.JFrame {

    /**
     * Creates new form Editar
     */
    String foto = "";
    public Selecao() {
        initComponents();
           
        this.setLocationRelativeTo(null);
        //jTtabela.getColumnModel().getColumnIndex("Foto");
        jTtabela.setModel(LivroDAO.listarTM(""));
        MetodosAuxiliares.ajustarColunas(jTtabela);
        
        String os = "";
        os = System.getProperty("os.name");
            
           
        if (os.equals("Windows 10")) {
            
            Image imagem = getToolkit().getImage(".\\Fotos\\DEFAULT.png");
            int altura = jLcarregaimagem.getHeight();
            int largura = jLcarregaimagem.getWidth();
            imagem = imagem.getScaledInstance(largura, altura, Image.SCALE_DEFAULT);
            jLcarregaimagem.setIcon(new ImageIcon(imagem));
        
        } else {
            
            Image imagem = getToolkit().getImage(".//Fotos//DEFAULT.png");
            int altura = jLcarregaimagem.getHeight();
            int largura = jLcarregaimagem.getWidth();
            imagem = imagem.getScaledInstance(largura, altura, Image.SCALE_DEFAULT);
            jLcarregaimagem.setIcon(new ImageIcon(imagem));
        }
        
        /*Image imagem = getToolkit().getImage(".\\Fotos\\DEFAULT.png");
        int altura = jLcarregaimagem.getHeight();
        int largura = jLcarregaimagem.getWidth();
        imagem = imagem.getScaledInstance(largura, altura, Image.SCALE_DEFAULT);
        jLcarregaimagem.setIcon(new ImageIcon(imagem));*/
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBincluir = new javax.swing.JButton();
        jBeditar = new javax.swing.JButton();
        jBexcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTtabela = new javax.swing.JTable();
        jTpesquisar = new javax.swing.JTextField();
        jLpesquisar = new javax.swing.JLabel();
        jBok = new javax.swing.JButton();
        jLcarregaimagem = new javax.swing.JLabel();
        jPBpagina = new javax.swing.JProgressBar();
        jLlivrolido = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBAdquirodos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manager");
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jBincluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/if_Add_27831.png"))); // NOI18N
        jBincluir.setText("Incluir");
        jBincluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBincluirActionPerformed(evt);
            }
        });

        jBeditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/if_editprofile_101844.png"))); // NOI18N
        jBeditar.setText("Editar");
        jBeditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeditarActionPerformed(evt);
            }
        });

        jBexcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/if_Remove_27874.png"))); // NOI18N
        jBexcluir.setText("Excluir");
        jBexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBexcluirActionPerformed(evt);
            }
        });

        jTtabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "null", "null", "null", "null", "null"
            }
        ));
        jTtabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTtabelaMouseClicked(evt);
            }
        });
        jTtabela.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTtabelaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTtabelaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTtabela);

        jTpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTpesquisarActionPerformed(evt);
            }
        });

        jLpesquisar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLpesquisar.setText("Pesquisar");

        jBok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/if_edit-find_118922.png"))); // NOI18N
        jBok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBokActionPerformed(evt);
            }
        });

        jLcarregaimagem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLlivrolido.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLlivrolido.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLlivrolido.setText("Lido");

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel1.setText("Capa");

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gerenciador de Livros");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/if_bookshelf_1055107 (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel3)
                .addGap(109, 109, 109)
                .addComponent(jLabel2)
                .addContainerGap(207, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jBAdquirodos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/if_bookcase_1228 (1).png"))); // NOI18N
        jBAdquirodos.setText("Gráfico de aquisições");
        jBAdquirodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdquirodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBincluir)
                .addGap(37, 37, 37)
                .addComponent(jBeditar)
                .addGap(34, 34, 34)
                .addComponent(jBexcluir)
                .addGap(228, 228, 228)
                .addComponent(jBAdquirodos)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLcarregaimagem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPBpagina, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLlivrolido)
                                .addGap(61, 61, 61))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(54, 54, 54)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLpesquisar)
                        .addGap(18, 18, 18)
                        .addComponent(jTpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBok, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                                .addComponent(jLpesquisar)
                                .addComponent(jTpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jBok))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLcarregaimagem, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLlivrolido)
                        .addGap(1, 1, 1)
                        .addComponent(jPBpagina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBincluir)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBexcluir)
                        .addComponent(jBAdquirodos))
                    .addComponent(jBeditar))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jBincluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBincluirActionPerformed
      
       new Inclusao().setVisible(true);
      
    }//GEN-LAST:event_jBincluirActionPerformed

     
    
    private void jBeditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeditarActionPerformed
       Integer linha = jTtabela.getSelectedRow();
       if(linha >=0){
           Integer id_livro = (Integer) jTtabela.getModel().getValueAt(linha, 0);
           String foto = (String) jTtabela.getModel().getValueAt(linha, 1);
           String titulo = (String) jTtabela.getModel().getValueAt(linha, 2);
           String descricao = (String) jTtabela.getModel().getValueAt(linha, 3);
           String  autor = (String) jTtabela.getModel().getValueAt(linha, 4);
           String editora = (String) jTtabela.getModel().getValueAt(linha, 5);
           String isbn = (String) jTtabela.getModel().getValueAt(linha, 6);
           Integer paginas = (Integer) jTtabela.getModel().getValueAt(linha, 7);
           Integer pag_lidas = (Integer) jTtabela.getModel().getValueAt(linha, 8);
           String adquirido = (String) jTtabela.getModel().getValueAt(linha, 9);
           
           new Edicao(id_livro, foto, titulo, descricao, 
                      autor, editora, isbn, paginas,
                       pag_lidas, adquirido).setVisible(true);
       }
       else{
           JOptionPane.showMessageDialog(null, "Selecione um livro");
       }
    }//GEN-LAST:event_jBeditarActionPerformed

    private void jTtabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTtabelaMouseClicked
        Integer linha = jTtabela.getSelectedRow();
       
        if(linha >=0){
            foto = (String) jTtabela.getModel().getValueAt(linha, 1);
            
        }
            Image imagem = getToolkit().getImage(foto);
            int altura = jLcarregaimagem.getHeight();
            int largura = jLcarregaimagem.getWidth(); 
            imagem = imagem.getScaledInstance(largura, altura, Image.SCALE_DEFAULT);
            jLcarregaimagem.setIcon(new ImageIcon(imagem)); 
            
            this.setTitle("Barra de Progresso");
            
            jPBpagina.setMinimum(0);
            jPBpagina.setMaximum(100);
            jPBpagina.setStringPainted(true);
            
            int pag = (int) jTtabela.getValueAt(jTtabela.getSelectedRow(), 7);
            int pag_lida = (int) jTtabela.getValueAt(jTtabela.getSelectedRow(), 8);
            int resultado = MetodosAuxiliares.Barra(pag, pag_lida);
            
            jPBpagina.setValue(resultado);
    }//GEN-LAST:event_jTtabelaMouseClicked

    private void jBexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBexcluirActionPerformed
        Integer linha = jTtabela.getSelectedRow();
        if(linha >= 0){
            Integer id_livro = (Integer) jTtabela.getModel().getValueAt(linha, 0);
            if(JOptionPane.showConfirmDialog(null, "Confirma exclusão?")==0){
                LivroDAO.excluir(id_livro);
                jTtabela.setModel(LivroDAO.listarTM(""));
            }
        }else{
           JOptionPane.showMessageDialog(null, "Selecione um livro");
       }
    }//GEN-LAST:event_jBexcluirActionPerformed

    private void jTpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTpesquisarActionPerformed
        
    }//GEN-LAST:event_jTpesquisarActionPerformed

    private void jBokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBokActionPerformed
        jTtabela.setModel(LivroDAO.listarTM(jTpesquisar.getText()));
        MetodosAuxiliares.ajustarColunas(jTtabela);
        jTpesquisar.setText("");
    }//GEN-LAST:event_jBokActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        jTtabela.setModel(LivroDAO.listarTM(""));
        MetodosAuxiliares.ajustarColunas(jTtabela);
    }//GEN-LAST:event_formWindowGainedFocus

    private void jBAdquirodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdquirodosActionPerformed
        //implementar
        int total, adquiridos;
        
        adquiridos = LivroDAO.livrosAdquiridos();
        total = LivroDAO.totalLivros();
        Grafico ad = new Grafico(adquiridos, total);
        ad.setLocationRelativeTo(null);
        ad.setVisible(true);
    }//GEN-LAST:event_jBAdquirodosActionPerformed

    private void jTtabelaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTtabelaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTtabelaKeyPressed

    private void jTtabelaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTtabelaKeyReleased
        Integer linha = jTtabela.getSelectedRow();
       
        if(linha >=0){
            foto = (String) jTtabela.getModel().getValueAt(linha, 1);
        }
            Image imagem = getToolkit().getImage(foto);
            int altura = jLcarregaimagem.getHeight();
            int largura = jLcarregaimagem.getWidth();
            imagem = imagem.getScaledInstance(largura, altura, Image.SCALE_DEFAULT);
            jLcarregaimagem.setIcon(new ImageIcon(imagem)); 
            
            this.setTitle("Barra de Progresso");
            
            jPBpagina.setMinimum(0);
               
            jPBpagina.setMaximum(100);
            
            jPBpagina.setStringPainted(true);
            
            int pag = (int) jTtabela.getValueAt(jTtabela.getSelectedRow(), 7);
            int pag_lida = (int) jTtabela.getValueAt(jTtabela.getSelectedRow(), 8);
            int resultado = MetodosAuxiliares.Barra(pag, pag_lida);
            
            jPBpagina.setValue(resultado);
    }//GEN-LAST:event_jTtabelaKeyReleased
    

        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Selecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Selecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Selecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Selecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Selecao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAdquirodos;
    private javax.swing.JButton jBeditar;
    private javax.swing.JButton jBexcluir;
    private javax.swing.JButton jBincluir;
    private javax.swing.JButton jBok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLcarregaimagem;
    private javax.swing.JLabel jLlivrolido;
    private javax.swing.JLabel jLpesquisar;
    private javax.swing.JProgressBar jPBpagina;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTpesquisar;
    private javax.swing.JTable jTtabela;
    // End of variables declaration//GEN-END:variables
}
